/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siakad;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Year;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ithoib
 */
public class mahasiswanew extends javax.swing.JFrame {

    /**
     * Creates new form mahasiswanew
     */
    public mahasiswanew() {
        initComponents();
        comboProdi();
        comboAngaktan();
        load_table_mhs();
        kosongi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gKel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rLaki = new javax.swing.JRadioButton();
        rPere = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTempatLahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAsal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cAngkatan = new javax.swing.JComboBox<>();
        cProdi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        cAgama = new javax.swing.JComboBox<>();
        txtTglLahir = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMhs = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bTutup = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kelamin");

        gKel.add(rLaki);
        rLaki.setText("Laki-Laki");

        gKel.add(rPere);
        rPere.setText("Perempuan");
        rPere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPereActionPerformed(evt);
            }
        });

        jLabel4.setText("Agama");

        jLabel5.setText("Tempat Lahir");

        jLabel6.setText("Tanggal Lahir");

        jLabel8.setText("No. HP");

        txtHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPActionPerformed(evt);
            }
        });

        jLabel9.setText("Angkatan");

        jLabel10.setText("Asal Sekolah");

        jLabel11.setText("Program Studi");

        jLabel7.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        cAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));

        txtTglLahir.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTglLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cAgama, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAsal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHP, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(rLaki)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rPere))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNIM, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTempatLahir, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cAngkatan, javax.swing.GroupLayout.Alignment.LEADING, 0, 286, Short.MAX_VALUE)
                        .addComponent(cProdi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rLaki)
                    .addComponent(rPere))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 321, 640));

        jTMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMhsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTMhs);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 880, 460));

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        getContentPane().add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, -1));

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        getContentPane().add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 100, -1));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, -1));

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        getContentPane().add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 100, -1));

        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });
        getContentPane().add(bTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 610, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 330, -1));

        jLabel12.setText("Cari:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 103, -1, -1));

        setSize(new java.awt.Dimension(1240, 699));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void rPereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPereActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        String nim = txtNIM.getText();
        String nama = txtNama.getText();
        String kelamin;
        if(rLaki.isSelected()){
            kelamin = "L";
        } else if(rPere.isSelected()){
            kelamin = "P";
        } else {
            kelamin = "";
        }
        String agama = cAgama.getSelectedItem().toString();
        String tempatLahir = txtTempatLahir.getText();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tglLahir = dateFormat.format(txtTglLahir.getDate());
        String noHP = txtHP.getText();
        int angkatan = Integer.parseInt(cAngkatan.getSelectedItem().toString());
        String asalSekolah = txtAsal.getText();
        String prodi = cProdi.getSelectedItem().toString();
        String alamat = txtAlamat.getText();
        try {
            String sql = "INSERT INTO mahasiswa(nim,nama,jenis_kelamin,agama,tempat_lahir,tgl_lahir,prodi,alamat,no_hp,asal_sekolah,angkatan) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nim);
            pst.setString(2, nama);
            pst.setString(3, kelamin);
            pst.setString(4, agama);
            pst.setString(5, tempatLahir);
            pst.setString(6, tglLahir);
            pst.setString(7, prodi);
            pst.setString(8, alamat);
            pst.setString(9, noHP);
            pst.setString(10, asalSekolah);
            pst.setInt(11, angkatan);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Penyimpanan Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table_mhs();
        kosongi();
        
    }//GEN-LAST:event_bTambahActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bTutupActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        kosongi();
    }//GEN-LAST:event_bResetActionPerformed

    private void jTMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMhsMouseClicked
        try {
            // TODO add your handling code here:
            int baris = jTMhs.rowAtPoint(evt.getPoint());
            txtNIM.setText(jTMhs.getValueAt(baris, 0).toString());
            txtNIM.setEditable(false);
            txtNama.setText(jTMhs.getValueAt(baris, 1).toString());
            cProdi.setSelectedItem(jTMhs.getValueAt(baris, 2).toString());
            String JK = jTMhs.getValueAt(baris, 3).toString();
            if(JK.equals("L")){
                rLaki.setSelected(true);
            } else {
                rPere.setSelected(true);
            }
            cAgama.setSelectedItem(jTMhs.getValueAt(baris, 4).toString());
            txtTempatLahir.setText(jTMhs.getValueAt(baris,5).toString());
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(jTMhs.getValueAt(baris, 6).toString());
            txtTglLahir.setDate(date);
            txtHP.setText(jTMhs.getValueAt(baris, 7).toString());
            cAngkatan.setSelectedItem(jTMhs.getValueAt(baris, 8).toString());
            txtAsal.setText(jTMhs.getValueAt(baris, 9).toString());
            txtAlamat.setText(jTMhs.getValueAt(baris, 10).toString());
        } catch (ParseException ex) {
            Logger.getLogger(mahasiswanew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTMhsMouseClicked

    private void txtHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        String nim = txtNIM.getText();
        try {
            String sql = "DELETE FROM mahasiswa WHERE nim=?";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nim);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table_mhs();
        kosongi();
    }//GEN-LAST:event_bHapusActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String nim = txtNIM.getText();
        String nama = txtNama.getText();
        String kelamin;
        if(rLaki.isSelected()){
            kelamin = "L";
        } else if(rPere.isSelected()){
            kelamin = "P";
        } else {
            kelamin = "";
        }
        String agama = cAgama.getSelectedItem().toString();
        String tempatLahir = txtTempatLahir.getText();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tglLahir = dateFormat.format(txtTglLahir.getDate());
        String noHP = txtHP.getText();
        int angkatan = Integer.parseInt(cAngkatan.getSelectedItem().toString());
        String asalSekolah = txtAsal.getText();
        String prodi = cProdi.getSelectedItem().toString();
        String alamat = txtAlamat.getText();
        try {
            String sql = "UPDATE mahasiswa SET nama=?, jenis_kelamin=?, agama=?, tempat_lahir=?, tgl_lahir=?, prodi=?, alamat=?, no_hp=?, asal_sekolah=?, angkatan=? WHERE nim=?";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, kelamin);
            pst.setString(3, agama);
            pst.setString(4, tempatLahir);
            pst.setString(5, tglLahir);
            pst.setString(6, prodi);
            pst.setString(7, alamat);
            pst.setString(8, noHP);
            pst.setString(9, asalSekolah);
            pst.setInt(10, angkatan);
            pst.setString(11, nim);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table_mhs();
        kosongi();
    }//GEN-LAST:event_bUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswanew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswanew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswanew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswanew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahasiswanew().setVisible(true);
            }
        });
    }
    
    private void comboAngaktan(){
        int year = Year.now().getValue();
        for(int i=2021;i<=year+100;i++){
            String tahun = String.valueOf(i);
            cAngkatan.addItem(tahun);
        }
    }
    private void comboProdi(){
        try {
  
            String sql = "SELECT * FROM prodi";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                cProdi.addItem(res.getString("kode_prodi"));
            }
        } catch (Exception e) {
        }
        cProdi.setSelectedItem(null);
    
    }
    private void load_table_mhs() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIM");
        model.addColumn("Nama");
        model.addColumn("Prodi");
        model.addColumn("L/P");
        model.addColumn("Agama");
        model.addColumn("Tempat Lahir");
        model.addColumn("Tgl. Lahir");
        model.addColumn("Np. HP");
        model.addColumn("Angkatan");
        model.addColumn("Asal Sekolah");
        model.addColumn("Alamat");
        
        try {
  
            String sql = "SELECT * FROM mahasiswa";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getString("nim"),res.getString("nama"),res.getString("prodi"),res.getString("jenis_kelamin"),res.getString("agama"),res.getString("tempat_lahir"),res.getString("tgl_lahir"),res.getString("no_hp"),res.getString("angkatan"),res.getString("asal_sekolah"),res.getString("alamat")});
            }
            jTMhs.setModel(model);
        } catch (Exception e) {
        }
    }
    private void kosongi(){
        txtNIM.setText(null);
        txtNama.setText(null);
        txtTempatLahir.setText(null);
        txtTglLahir.setCalendar(null);
        txtAsal.setText(null);
        txtHP.setText(null);
        txtAlamat.setText(null);
        cProdi.setSelectedItem(null);
        cAgama.setSelectedItem(null);
//        int year = Year.now().getValue();
        cAngkatan.setSelectedItem(null);
        gKel.clearSelection();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTutup;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cAgama;
    private javax.swing.JComboBox<String> cAngkatan;
    private javax.swing.JComboBox<String> cProdi;
    private javax.swing.ButtonGroup gKel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTMhs;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton rLaki;
    private javax.swing.JRadioButton rPere;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTempatLahir;
    private com.toedter.calendar.JDateChooser txtTglLahir;
    // End of variables declaration//GEN-END:variables
}
