/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siakad;

import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ithoib
 */
public class prodi extends javax.swing.JFrame {

    /**
     * Creates new form prodi
     */
    public prodi() {
        initComponents();
        comboFakultas();
        load_table_prodi();
        kosongi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jKodeProdi = new javax.swing.JTextField();
        jNamaProdi = new javax.swing.JTextField();
        cFakultas = new javax.swing.JComboBox<>();
        jTambahProdi = new javax.swing.JButton();
        jUbahProdi = new javax.swing.JButton();
        jHapusProdi = new javax.swing.JButton();
        jResetProdi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdi = new javax.swing.JTable();
        jTutupProdi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Program Studi"));

        jLabel1.setText("Kode Program Studi");

        jLabel2.setText("Nama Program Studi");

        jLabel3.setText("Fakultas");

        jKodeProdi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jKodeProdi.setOpaque(true);

        jNamaProdi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jNamaProdi.setOpaque(true);

        cFakultas.setOpaque(true);

        jTambahProdi.setText("Tambah");
        jTambahProdi.setOpaque(true);
        jTambahProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTambahProdiActionPerformed(evt);
            }
        });

        jUbahProdi.setText("Ubah");
        jUbahProdi.setOpaque(true);
        jUbahProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUbahProdiActionPerformed(evt);
            }
        });

        jHapusProdi.setText("Hapus");
        jHapusProdi.setOpaque(true);
        jHapusProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusProdiActionPerformed(evt);
            }
        });

        jResetProdi.setText("Reset");
        jResetProdi.setOpaque(true);
        jResetProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetProdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTambahProdi)
                        .addGap(18, 18, 18)
                        .addComponent(jUbahProdi)
                        .addGap(18, 18, 18)
                        .addComponent(jHapusProdi)
                        .addGap(18, 18, 18)
                        .addComponent(jResetProdi))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jKodeProdi)
                        .addComponent(jNamaProdi)
                        .addComponent(cFakultas, 0, 464, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jKodeProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNamaProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTambahProdi)
                    .addComponent(jUbahProdi)
                    .addComponent(jHapusProdi)
                    .addComponent(jResetProdi))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 660, 180));

        jTProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTProdi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, 660, 160));

        jTutupProdi.setText("Tutup");
        jTutupProdi.setOpaque(true);
        jTutupProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTutupProdiActionPerformed(evt);
            }
        });
        getContentPane().add(jTutupProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        setSize(new java.awt.Dimension(682, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTutupProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTutupProdiActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jTutupProdiActionPerformed

    private void jTambahProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahProdiActionPerformed
        // TODO add your handling code here:
        int idFak = Integer.parseInt(getFakID(cFakultas.getSelectedItem().toString()));
        String kodeProdi = jKodeProdi.getText();
        String namaProdi = jNamaProdi.getText();
        try {
            String sql = "INSERT INTO prodi(kode_prodi,nama_prodi,fakultas) VALUES('" + kodeProdi + "','" + namaProdi + "'," + idFak + ")";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table_prodi();
        kosongi();
    }//GEN-LAST:event_jTambahProdiActionPerformed

    private void jResetProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetProdiActionPerformed
        // TODO add your handling code here:
        kosongi();
    }//GEN-LAST:event_jResetProdiActionPerformed

    private void jUbahProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUbahProdiActionPerformed
        // TODO add your handling code here:
        int idFak = Integer.parseInt(getFakID(cFakultas.getSelectedItem().toString()));
        String kodeProdi = jKodeProdi.getText();
        String namaProdi = jNamaProdi.getText();
        try {
            String sql = "UPDATE prodi SET nama_prodi='" + namaProdi + "', fakultas=" + idFak + " WHERE kode_prodi='" + kodeProdi + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table_prodi();
        kosongi();
    }//GEN-LAST:event_jUbahProdiActionPerformed

    private void jHapusProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusProdiActionPerformed
        // TODO add your handling code here:
        String kodeProdi = jKodeProdi.getText();
        try {
            String sql = "DELETE FROM prodi WHERE kode_prodi='" + kodeProdi + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table_prodi();
        kosongi();
    }//GEN-LAST:event_jHapusProdiActionPerformed

    private void jTProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdiMouseClicked
        // TODO add your handling code here:
        int baris = jTProdi.rowAtPoint(evt.getPoint());
        String kodeProdi = jTProdi.getValueAt(baris, 0).toString();
        jKodeProdi.setText(kodeProdi);
        jKodeProdi.setEditable(false);
        String namaProdi = jTProdi.getValueAt(baris, 1).toString();
        jNamaProdi.setText(namaProdi);
        String namaFakultas = jTProdi.getValueAt(baris, 2).toString();
        cFakultas.setSelectedItem(namaFakultas);
    }//GEN-LAST:event_jTProdiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prodi().setVisible(true);
            }
        });
    }
    
    private void load_table_prodi() {
        DefaultTableModel modelprod = new DefaultTableModel();
        modelprod.addColumn("Kode Prodi");
        modelprod.addColumn("Nama Prodi");
        modelprod.addColumn("Fakultas");
        try {
  
            String sql = "SELECT p.kode_prodi,p.nama_prodi,f.nama_fakultas FROM prodi p LEFT JOIN fakultas f ON p.fakultas=f.id_fakultas";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                modelprod.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
            }
            jTProdi.setModel(modelprod);
        } catch (Exception e) {
        }

    }

    public prodi(JComboBox<String> cFakultas, JButton jHapusProdi, JTextField jKodeProdi, JLabel jLabel1, JLabel jLabel2, JLabel jLabel3, JTextField jNamaProdi, JPanel jPanel1, JButton jResetProdi, JScrollPane jScrollPane1, JTable jTProdi, JButton jTambahProdi, JButton jTutupProdi, JButton jUbahProdi) throws HeadlessException {
        this.cFakultas = cFakultas;
        this.jHapusProdi = jHapusProdi;
        this.jKodeProdi = jKodeProdi;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jNamaProdi = jNamaProdi;
        this.jPanel1 = jPanel1;
        this.jResetProdi = jResetProdi;
        this.jScrollPane1 = jScrollPane1;
        this.jTProdi = jTProdi;
        this.jTambahProdi = jTambahProdi;
        this.jTutupProdi = jTutupProdi;
        this.jUbahProdi = jUbahProdi;
    }
    
   
    private String getFakID(String nama){
        try {
  
            String sql = "SELECT * FROM fakultas WHERE nama_fakultas='" + nama + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                return res.getString("id_fakultas");
            }
        } catch (Exception e) {
        }
        return "";
    }
    private void comboFakultas(){
        try {
  
            String sql = "SELECT * FROM fakultas";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                cFakultas.addItem(res.getString("nama_fakultas"));
            }
        } catch (Exception e) {
        }
        
    
    }

    private void kosongi(){
        cFakultas.setSelectedItem(null);
        jKodeProdi.setText(null);
        jKodeProdi.setEditable(true);
        jNamaProdi.setText(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cFakultas;
    private javax.swing.JButton jHapusProdi;
    private javax.swing.JTextField jKodeProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jNamaProdi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jResetProdi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdi;
    private javax.swing.JButton jTambahProdi;
    private javax.swing.JButton jTutupProdi;
    private javax.swing.JButton jUbahProdi;
    // End of variables declaration//GEN-END:variables
}
